#!/bin/bash

if ["$1" = "1"]
then
  echo "Testing for avr (Uno)"
  arduino --verify --board arduino:avr:uno ./Control_over_serial/Control_over_serial.ino 
fi

if ["$1" = "2"]
then
  echo "Testing for sam (Due)"
  arduino --verify --board arduino:sam:due ./Control_over_serial/Control_over_serial.ino 
fi
